### ISSUE TITLE
Error when the widget is too big and does not fit in the screen. 

### ISSUE THREAD

**Issue by rr8733380** [notDmDrl/pull_down_button#20] opened 2023-03-21 19:13 UTC
When a widget has a greater height than the screen height, sometimes an error occurs.

Here is my code:
```
return PullDownButton(
  itemBuilder: (context) {
    return [...items];
  },
  buttonBuilder: (context, showMenu) {
    return GestureDetector(
      onTap: () async {
        showMenu();
      },
      child: BigHeightWidget,
    );
  },
  position: PullDownMenuPosition.automatic,
);
```
Here is the error:

```
The following assertion was thrown during performLayout():
BoxConstraints has non-normalized height constraints.

The offending constraints were: BoxConstraints(0.0<=w<=390.0, 0.0<=h<=-236.3; NOT NORMALIZED)
The relevant error-causing widget was
GetMaterialApp
main.dart:60
When the exception was thrown, this was the stack
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError
box.dart:525
#1      BoxConstraints.debugAssertIsValid.<anonymous closure>
box.dart:568
#2      BoxConstraints.debugAssertIsValid
box.dart:583
#3      BoxConstraints.deflate
box.dart:194
#4      _PopupMenuRouteLayout.getConstraintsForChild
route_layout.dart:68
#5      RenderCustomSingleChildLayoutBox.performLayout
shifted_box.dart:1303
#6      RenderObject.layout
object.dart:2189
#7      RenderBox.layout
box.dart:2430
#8      RenderProxyBoxMixin.performLayout
proxy_box.dart:120
#9      RenderObject.layout
object.dart:2189
#10     RenderBox.layout
box.dart:2430
#11     RenderProxyBoxMixin.performLayout
proxy_box.dart:120
#12     RenderObject.layout
object.dart:2189
#13     RenderBox.layout
box.dart:2430
#14     RenderProxyBoxMixin.performLayout
proxy_box.dart:120
#15     RenderObject.layout
object.dart:2189
#16     RenderBox.layout
box.dart:2430
#17     RenderProxyBoxMixin.performLayout
proxy_box.dart:120
#18     RenderObject.layout
object.dart:2189
#19     RenderBox.layout
box.dart:2430
#20     RenderProxyBoxMixin.performLayout
proxy_box.dart:120
#21     RenderOffstage.performLayout
proxy_box.dart:3815
#22     RenderObject.layout
object.dart:2189
#23     RenderBox.layout
box.dart:2430
#24     RenderProxyBoxMixin.performLayout
proxy_box.dart:120
#25     RenderObject.layout
object.dart:2189
#26     RenderBox.layout
box.dart:2430
#27     _RenderTheatre.performLayout
overlay.dart:856
#28     RenderObject._layoutWithoutResize
object.dart:2027
#29     PipelineOwner.flushLayout
object.dart:1020
#30     RendererBinding.drawFrame
binding.dart:516
#31     WidgetsBinding.drawFrame
binding.dart:865
#32     RendererBinding._handlePersistentFrameCallback
binding.dart:381
#33     SchedulerBinding._invokeFrameCallback
binding.dart:1289
#34     SchedulerBinding.handleDrawFrame
binding.dart:1218
#35     SchedulerBinding._handleDrawFrame
binding.dart:1076
#36     _invoke (dart:ui/hooks.dart:145:13)
#37     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#38     _drawFrame (dart:ui/hooks.dart:112:31)
The following RenderObject was being processed when the exception was fired: RenderCustomSingleChildLayoutBox#2e4d0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderCustomSingleChildLayoutBox#2e4d0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=390.0, h=844.0)
    size: Size(390.0, 844.0)
    child: RenderTransform#04a42 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0)
        constraints: MISSING
        size: MISSING
        transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
        origin: null
        alignment: Alignment.topRight
        textDirection: ltr
        transformHitTests: true
        child: RenderDecoratedBox#9706c NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            parentData: <none>
            constraints: MISSING
            size: MISSING
            decoration: BoxDecoration
                boxShadow: BoxShadow(CupertinoDynamicColor(*color = Color(0x00000000)*, darkColor = Color(0x0000ff00), resolved by: RoutePullDownMenu), Offset(0.0, 0.0), 0.0, 0.0, BlurStyle.normal)
            configuration: ImageConfiguration(bundle: PlatformAssetBundle#49280(), devicePixelRatio: 3.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
            child: RenderAnimatedOpacity#c8b3b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                parentData: <none>
                constraints: MISSING
                size: MISSING
                opacity: ClampedAnimation#c1271(▶)
                child: RenderClipRRect#5aa72 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
                    parentData: <none>
                    constraints: MISSING
                    size: MISSING
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Updated layout information required for RenderTransform#04a42 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
object.dart:1
Failed assertion: line 3232 pos 12: '!_needsLayout'

════════════════════════════════════════════════════════════════════════════════
```

**Comment by notDmDrl** [comment] 2023-03-21 21:19
Duplicate of [#21]

**Closed by notDmDrl** 2023-03-21 21:19 UTC
Labels: bug

**Comment by rr8733380** [comment] 2023-03-21 21:22
I'm sorry, you don't plan to fix that?

**Comment by notDmDrl** [comment] 2023-03-21 21:23
See [comment](https://github.com/notDmDrl/pull_down_button/issues/21#issuecomment-1478597467)
