### ISSUE TITLE
Performance Drop in PullDownButton Animation on Real iOS Devices

### ISSUE THREAD

**Issue by andychucs** [notDmDrl/pull_down_button#39] opened 2023-11-16 13:36 UTC
performance issue with the pop-up animation of the PullDownButton. 

This problem does not occur on the iOS Simulator, but when testing on real devices (iPhone 13 Pro and iPad Air 3 running iOS 17), there is a noticeable drop in frame rate that can be observed visually. Interestingly, when recording the screen, the video appears to be smooth.

I tried opening the performance overlay and noticed that the GPU graph has red bars.  I'm not sure what could be causing this. Do you have any insights?

![C48C728C-363B-4D75-8C55-38170B5D2AE7](https://github.com/notDmDrl/pull_down_button/assets/24852023/9cba4b85-4ce7-4dc2-86bc-1c42d542d8e8)

**Comment by notDmDrl** [comment] 2023-11-16 15:57
Hi @andychucs,

Unfortunately, I currently don't have an opportunity to look at this as I no longer have access to Mac/iPhone. So I can't even test a possible fix 😞.

What Flutter version are you using and do you have Impeller enabled? There were some issues with an older version of Impeller performance [here](https://github.com/notDmDrl/pull_down_button/issues/10).

> I tried opening the performance overlay and noticed that the GPU graph has red bars. I'm not sure what could be causing this. Do you have any insights?

Those spikes are probably caused by opening/closing the menu as there is a lot of rendering happening. If I had to guess, it is probably because of the animation of the blurred menu container. Can you try replacing the default menu background color with an opaque one (opaque colors disable blur)? The default values can be found [here](https://github.com/notDmDrl/pull_down_button/blob/6fc513a9718d07c53e6837f6cf98068fe5ca5188/lib/src/theme/route_theme.dart#L192).

**Comment by andychucs** [comment] 2023-11-16 16:47
@notDmDrl  thank you reply.  

I use Flutter 3.16, Impeller is default enable on iOS, and Impeller is available on Android devices that support Vulkan today. (I have not test on Android now)

It's looks similar with #10 . I will keep identify the issue. If there is any new progress, I will update it here.

**Comment by andychucs** [comment] 2023-11-17 08:40
I test to pop up a PullDownMenu by other way. Here are two examples, the second one(use [popover](https://pub.dev/packages/popover) ) looks more smooth, but of course it has fewer animations and functions. I haven't closely compared the behavioral differences between the two yet.

```dart
Widget pullDownButton() {
  return PullDownButton(
    itemBuilder: (context) => [
      PullDownMenuItem(
        title: 'Menu item',
        onTap: () {},
      ),
      PullDownMenuItem(
        title: 'Menu item 2',
        onTap: () {},
      ),
    ],
    buttonBuilder: (context, showMenu) => GestureDetector(
      onTap: showMenu,
      child: Container(
        color: Colors.black,
        width: 20,
        height: 10,
      ),
    ),
  );
}
```

```dart
Widget popByShowPopover() {
  return Builder(
    builder: (BuildContext context) {
      return GestureDetector(
        onTap: () => showPopover(
             backgroundColor: Colors.transparent,
             shadow: [
               const BoxShadow(
                 color: Color.fromRGBO(0, 0, 0, 0.2),
                 blurRadius: 64,
               )
            ],
            barrierColor: Colors.transparent,
            context: context,
            arrowHeight: 0,
            arrowWidth: 0,
            bodyBuilder: (_) {
              return PullDownMenu(items: [
                PullDownMenuItem(
                  title: 'Menu item',
                  onTap: () {},
                ),
                PullDownMenuItem(
                  title: 'Menu item 2',
                  onTap: () {},
                ),
              ]);
            }),
        child: Container(
          color: Colors.black,
          width: 20,
          height: 10,
        ), 
      );
    },
  );
}

```

**Comment by jwang0512** [comment] 2024-02-03 15:19
facing the same problem here, any suggestion pls?

**Comment by notDmDrl** [comment] 2024-02-03 15:37
Hi @jwang0512 (and also @andychucs for that matter).

Based on this [quick search in Flutter repo](https://github.com/flutter/flutter/issues?page=2&q=is%3Aissue+is%3Aopen+impeller+blur) - there are still a lot of issues with blurs on Impeller (including performance).

As for suggestions - same as always with blurs, try using a fully opaque background color for menus as it will disable blur entirely (see https://github.com/notDmDrl/pull_down_button/issues/39#issuecomment-1814745066). Or you could try the latest Flutter beta as, apparently, there are some improvements for this case.

**Comment by jwang0512** [comment] 2024-02-04 17:06
Thank you @notDmDrl
I like this component very much, it really helps.  :)

**Comment by andychucs** [comment] 2024-03-02 03:28
@jwang0512 @notDmDrl  in Flutter 3.19.2,  looks like this issue have improved, raster avg down to 5.4 ms/frame in same case.

**Comment by jwang0512** [comment] 2024-04-11 18:37
> @jwang0512 @notDmDrl after upgrade to Flutter 3.19.2, looks like this issue have improved, raster avg down to 5.4 ms/frame in same case. ![IMG_2092](https://private-user-images.githubusercontent.com/24852023/309438306-3346054d-ea0c-4183-83f4-08d90f3c57df.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjAzNzMsIm5iZiI6MTcxMjg2MDA3MywicGF0aCI6Ii8yNDg1MjAyMy8zMDk0MzgzMDYtMzM0NjA1NGQtZWEwYy00MTgzLTgzZjQtMDhkOTBmM2M1N2RmLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE4Mjc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OWU1MTkxZmVlYjk0YmZjNjdlNzRmYmQwYTE4NDhlODA1MTRmYWE1MzVlZWE2MzA1Nzk0ZDNiOGU1ZjUwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mKjVML11kplFreflAJo2eLbENUbqYVyeV8CPGk651xQ)

Yes, just upgraded to 3.19.3 and it works great.  😄

**Comment by notDmDrl** [comment] 2024-04-11 19:13
@jwang0512 those are excellent news 😄

This issue can be closed then. If someone encounters performance issues on iOS with Impeller, feel free to comment here (so I reopen this issue) or create a new one.

**Closed by notDmDrl** 2024-04-11 19:13 UTC
Labels: bug, flutter-specific
